export const authTestIds = {
  login: {
    form: "auth-login-form",
    emailInput: "auth-login-email-input",
    passwordInput: "auth-login-password-input",
    submitButton: "auth-login-submit-button",
    forgotPasswordLink: "auth-login-forgot-password-link",
    registerLink: "auth-login-register-link",
    googleButton: "auth-login-google-button",
    errorBanner: "auth-login-error-banner",
  },
  register: {
    form: "auth-register-form",
    nameInput: "auth-register-name-input",
    lastNameInput: "auth-register-last-name-input",
    identificationInput: "auth-register-identification-input",
    phoneInput: "auth-register-phone-input",
    emailInput: "auth-register-email-input",
    passwordInput: "auth-register-password-input",
    confirmPasswordInput: "auth-register-confirm-password-input",
    clientOption: "auth-register-client-option",
    nurseOption: "auth-register-nurse-option",
    submitButton: "auth-register-submit-button",
    loginLink: "auth-register-login-link",
    googleButton: "auth-register-google-button",
    errorBanner: "auth-register-error-banner",
    successBanner: "auth-register-success-banner",
  },
  forgotPassword: {
    form: "auth-forgot-password-form",
    emailInput: "auth-forgot-password-email-input",
    submitButton: "auth-forgot-password-submit-button",
    enterCodeButton: "auth-forgot-password-enter-code-button",
    resendButton: "auth-forgot-password-resend-button",
    successBanner: "auth-forgot-password-success-banner",
    errorBanner: "auth-forgot-password-error-banner",
    backToLoginLink: "auth-forgot-password-login-link",
  },
  resetPassword: {
    form: "auth-reset-password-form",
    emailInput: "auth-reset-password-email-input",
    codeInput: "auth-reset-password-code-input",
    passwordInput: "auth-reset-password-password-input",
    confirmPasswordInput: "auth-reset-password-confirm-password-input",
    submitButton: "auth-reset-password-submit-button",
    successBanner: "auth-reset-password-success-banner",
    errorBanner: "auth-reset-password-error-banner",
    requestAnotherCodeLink: "auth-reset-password-request-another-code-link",
  },
  account: {
    sessionCard: "auth-account-session-card",
    accessCard: "auth-account-access-card",
    emailValue: "auth-account-email-value",
    googleButton: "auth-account-google-button",
    loginButton: "auth-account-login-button",
    registerButton: "auth-account-register-button",
    logoutButton: "auth-account-logout-button",
  },
};
