export const careRequestTestIds = {
  list: {
    page: "care-list-page",
    summaryGrid: "care-list-summary-grid",
    summaryTotalCard: "care-list-summary-total-card",
    summaryPendingCard: "care-list-summary-pending-card",
    summaryApprovedCard: "care-list-summary-approved-card",
    summaryCompletedCard: "care-list-summary-completed-card",
    refreshButton: "care-list-refresh-button",
    createButton: "care-list-create-button",
    errorBanner: "care-list-error-banner",
    board: "care-list-board",
    emptyState: "care-list-empty-state",
    requestRow: (id: string) => `care-list-row-${id}`,
    requestDetailButton: (id: string) => `care-list-detail-button-${id}`,
  },
  detail: {
    page: "care-detail-page",
    backButton: "care-detail-back-button",
    refreshButton: "care-detail-refresh-button",
    mainGrid: "care-detail-main-grid",
    infoSection: "care-detail-info-section",
    statusChip: "care-detail-status-chip",
    fieldsGrid: "care-detail-fields-grid",
    field: (fieldName: string) => `care-detail-field-${fieldName}`,
    transitionsSection: "care-detail-transitions-section",
    assignmentSection: "care-detail-assignment-section",
    assignmentSelect: "care-detail-assignment-select",
    assignmentButton: "care-detail-assignment-button",
    actionsPanel: "care-detail-actions-panel",
    approveButton: "care-detail-approve-button",
    rejectButton: "care-detail-reject-button",
    completeButton: "care-detail-complete-button",
    pricingBreakdown: "care-detail-pricing-breakdown",
    pricingField: (fieldName: string) => `price-breakdown-${fieldName}`,
    verifyPricingButton: "price-breakdown-verify-button",
    verificationModal: "price-verification-modal",
    verificationSuccess: "price-verification-success",
    verificationDiscrepancies: "price-verification-discrepancies",
    verificationLimitation: "price-verification-limitation",
    verificationCloseButton: "price-verification-close-button",
  },
  create: {
    page: "care-create-page",
    form: "care-create-form",
    descriptionField: "care-create-description-field",
    suggestedNurseField: "care-create-suggested-nurse-field",
    serviceTypeSelect: "care-create-type-select",
    submitButton: "care-create-submit-button",
    clearButton: "care-create-clear-button",
    pricingEstimate: "care-create-pricing-estimate",
    feedbackBanner: "care-create-feedback-banner",
    submissionChecklist: "care-create-submission-checklist",
  },
};
