#!/bin/bash
# Script to set up mobile development environment
# This script detects your local IP and creates a .env.development.local file

echo "🔧 Setting up mobile development environment..."
echo ""

# Detect the local IP address (macOS/Linux)
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null)
    if [ -z "$LOCAL_IP" ]; then
        # Try en1 if en0 fails (some Macs use different interface names)
        LOCAL_IP=$(ipconfig getifaddr en1 2>/dev/null)
    fi
else
    # Linux
    LOCAL_IP=$(hostname -I | awk '{print $1}')
fi

if [ -z "$LOCAL_IP" ]; then
    echo "❌ Could not detect local IP address automatically."
    echo "Please enter your local IP address manually (e.g., 10.0.0.34):"
    read -r LOCAL_IP
fi

echo "📡 Detected local IP: $LOCAL_IP"
echo ""

# Ask for backend port (default 8080)
echo "Enter the backend port (default: 8080):"
read -r BACKEND_PORT
BACKEND_PORT=${BACKEND_PORT:-8080}

# Create .env.development.local
ENV_FILE=".env.development.local"
echo "📝 Creating $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# Generated by setup-mobile-dev.sh
# Configuration for mobile development
# Your local IP: $LOCAL_IP
VITE_API_BASE_URL=http://$LOCAL_IP:$BACKEND_PORT/api
EOF

echo "✅ Created $ENV_FILE with the following configuration:"
cat "$ENV_FILE"
echo ""

echo "🚀 Mobile development environment is ready!"
echo ""
echo "Next steps:"
echo "1. Make sure your backend is running on http://$LOCAL_IP:$BACKEND_PORT"
echo "2. Start the Vite dev server: npm start"
echo "3. Access from your mobile device: http://$LOCAL_IP:3000"
echo ""
echo "📖 For more information, see MOBILE_DEVELOPMENT.md"
